import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import InstanceProvider from "~/providers/instanceProvider";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function Layout({
  children,
  params,
}: PropsWithChildren<{
  params: { theme: string; instance: string };
}>) {
  // Add more data linked to instance/country
  const instanceData = {
    key: params.instance,
  };
  return <InstanceProvider data={instanceData}>{children}</InstanceProvider>;
}
